# Generated by Django 4.2.7 on 2024-03-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix_unitaire')),
                ('categorie_achat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('nb_enfant', models.IntegerField()),
                ('ville', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Csp',
            fields=[
                ('id_csp', models.AutoField(primary_key=True, serialize=False)),
                ('csp_lbl', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id_collecte', models.AutoField(primary_key=True, serialize=False)),
                ('prix_categorie', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
                ('qte_article', models.IntegerField()),
                ('montant_achat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collectes', to='indicateur.article')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collectes', to='indicateur.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_collecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_collecte', to='indicateur.collecte'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_csp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_csp', to='indicateur.csp'),
        ),
    ]
