# Generated by Django 4.2.7 on 2024-03-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_collecte',
        ),
    ]
