# Generated by Django 4.2.7 on 2024-03-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0002_remove_client_id_collecte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_csp',
        ),
        migrations.AddField(
            model_name='csp',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csps', to='indicateur.client'),
        ),
    ]
