# Generated by Django 4.2.7 on 2024-04-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0004_remove_csp_id_client_client_id_csp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecte',
            name='montant_achat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
